### ISSUE TITLE
`cached_download` no longer supported?

### ISSUE THREAD

**Issue by cjpatton** [XuandongZhao/PRC-Watermark#2]
Related to https://github.com/TencentARC/InstantMesh/issues/169, it looks like the version of huggingface_hug installed by the default dependencies no longer has the `cached_download` module. The code appears to be happy with an older version, 0.25.2.

**Comment by lagamura** [comment]
check the solution here https://github.com/huggingface/huggingface_hub/issues/2617

**Comment by cjpatton** [comment]
@XuandongZhao I can reproduce on main as follows:
```
(.venv) ➜  PRC-Watermark git:(main) python encode.py --test_num 10
^[[1;6DTraceback (most recent call last):
  File "/Users/chris/github.com/XuandongZhao/PRC-Watermark/encode.py", line 13, in <module>
    from src.baseline.treering_watermark import tr_detect, tr_get_noise
  File "/Users/chris/github.com/XuandongZhao/PRC-Watermark/src/baseline/treering_watermark.py", line 6, in <module>
    from diffusers import DDIMInverseScheduler
  File "/Users/chris/github.com/XuandongZhao/PRC-Watermark/.venv/lib/python3.11/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/Users/chris/github.com/XuandongZhao/PRC-Watermark/.venv/lib/python3.11/site-packages/diffusers/utils/__init__.py", line 36, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/Users/chris/github.com/XuandongZhao/PRC-Watermark/.venv/lib/python3.11/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/Users/chris/github.com/XuandongZhao/PRC-Watermark/.venv/lib/python3.11/site-packages/huggingface_hub/__init__.py)
```

Upgrading didn't work for me: I solved this by pinning `huggingface_hub==0.25.0` in requirements.txt.
