### ISSUE TITLE
Decoding encounters a `TypeError`

### ISSUE THREAD

**Issue by cjpatton** [XuandongZhao/PRC-Watermark#3]
I'm working on reproducing the test from the README. I've successfully generated an image with a watermark:
```
(venv) ➜  PRC-Watermark git:(cjpatton/bugs) ✗ time python3.11 encode.py --test_num 1
Namespace(test_num=1, method='prc', model_id='stabilityai/stable-diffusion-2-1-base', dataset_id='Gustavosta/Stable-Diffusion-Prompts', inf_steps=50, nowm=0, fpr=1e-05, prc_t=3)
Loaded PRC keys from file keys/prc_num_1_steps_50_fpr_1e-05_nowm_0.pkl
Saving original images to ./results/prc_num_1_steps_50_fpr_1e-05_nowm_0/original_images
No GPUs found. Use CPU.
/opt/homebrew/lib/python3.11/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 15.75it/s]
  0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]No GPUs found. Use CPU.
/opt/homebrew/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py:430: FutureWarning: The decode_latents method is deprecated and will be removed in 1.0.0. Please use VaeImageProcessor.postprocess(...) instead
  deprecate("decode_latents", "1.0.0", deprecation_message, standard_warn=False)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:59<00:00, 119.59s/it]
Done generating prc images
python3.11 encode.py --test_num 1  382.60s user 81.89s system 371% cpu 2:05.12 total
```

(Ignore the `No GPUs found. Use CPU.` This a `print()` on my debug branch.)

However checking for the watermark encounters an exception:
```
(venv) ➜  PRC-Watermark git:(cjpatton/bugs) ✗ time python3.11 decode.py --test_num 1
Namespace(test_num=1, method='prc', model_id='stabilityai/stable-diffusion-2-1-base', dataset_id='Gustavosta/Stable-Diffusion-Prompts', inf_steps=50, nowm=0, fpr=1e-05, prc_t=3, test_path='original_images')
No GPUs found. Use CPU.
No GPUs found. Use CPU.
/opt/homebrew/lib/python3.11/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 13.01it/s]
  0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]No GPUs found. Use CPU.
No GPUs found. Use CPU.
/opt/homebrew/lib/python3.11/site-packages/ldpc/_legacy_ldpc_v1/_legacy_bp_decoder.py:37: UserWarning: This is the old syntax for the `bp_decoder` from `ldpc v1`. Use the `BpDecoder` class from `ldpc v2` for additional features.
  warnings.warn("This is the old syntax for the `bp_decoder` from `ldpc v1`. Use the `BpDecoder` class from `ldpc v2` for additional features.")
  0%|                                                                                                                                                                  | 0/1 [28:55<?, ?it/s]
Traceback (most recent call last):
  File "/Users/chris/github.com/XuandongZhao/PRC-Watermark/decode.py", line 62, in <module>
    decoding_result = (Decode(decoding_key, reversed_prc) is not None)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chris/github.com/XuandongZhao/PRC-Watermark/src/prc.py", line 183, in Decode
    recovered_string = np.linalg.solve(ordered_generator_matrix[top_invertible_rows], GF(ordered_x_decoded[top_invertible_rows]))
                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/galois/_fields/_array.py", line 70, in __new__
    return super().__new__(cls, x, dtype, copy, order, ndmin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/galois/_domains/_array.py", line 55, in __new__
    x = cls._verify_array_like_types_and_values(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/galois/_fields/_array.py", line 147, in _verify_array_like_types_and_values
    raise TypeError(f"{cls.name} arrays must have integer dtypes, not {x.dtype}.")
TypeError: GF(2) arrays must have integer dtypes, not float64.
python3.11 decode.py --test_num 1  3371.33s user 1406.27s system 274% cpu 28:59.34 total
```

I'm still digging into the crypto, the LLM bits, and the code itself (I'm starting almost from scratch, to be honest). My best guess right now is that you would normally run this with CUDA enabled, and the bug only manifests if you try to do things on CPU, which is what I'm trying to do at the moment. (I'm on Apple Silicon and need to figure out how to make use of my GPU.)

Very naive question, but for the purpose of getting the code to "kind of work (TM)", do you think I could safely cast as an int here? I.e., `GF(int(ordered_x_decoded[top_inverible_rows]))`?

**Comment by XuandongZhao** [comment]
I found that it works in our local environment. Consider using the specific versions of these two packages:
```
galois==0.4.1  
ldpc==0.1.51  
```
