### ISSUE TITLE
Shape error after correcting dtype error

### ISSUE THREAD

**Issue by mr-sarthakgupta** [XuandongZhao/PRC-Watermark#4]
As described in https://github.com/XuandongZhao/PRC-Watermark/issues/3, there is an error due to different dtype than required which is easily fixed by changing the datatype of the array to np.int8

But after fixing I'm facing an error at line 134 in src/prc.py `Pi = np.prod(posteriors[parity_check_matrix.indices.reshape(r, t)], axis=1)`, the error has the following stacktrace:

```
Traceback (most recent call last):
  File "/scratch/vidit_a_mfs.iitr/reverse-mark/PRC-Watermark/decode.py", line 60, in <module>
    detection_result = Detect(decoding_key, reversed_prc)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/vidit_a_mfs.iitr/reverse-mark/PRC-Watermark/src/prc.py", line 134, in Detect
    Pi = np.prod(posteriors[parity_check_matrix.indices.reshape(r, t)], axis=1)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot reshape array of size 11833 into shape (15777,3)
```

I can't understand how to fix this. The only difference being that I'm using a different version of pytorch due to hardware compatibility issues

**Comment by mr-sarthakgupta** [comment]
Found a bug in my code caused while fixing the dtype errors. Sorry for this, closing this issue now.
